// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: CostSheetEntry.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct CostSheetEntry {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: CostSheetEntry.EntryType {
    get {return _type ?? .income}
    set {_type = newValue}
  }
  /// Returns true if `type` has been explicitly set.
  var hasType: Bool {return self._type != nil}
  /// Clears the value of `type`. Subsequent reads from it will return its default value.
  mutating func clearType() {self._type = nil}

  var amount: Float {
    get {return _amount ?? 0}
    set {_amount = newValue}
  }
  /// Returns true if `amount` has been explicitly set.
  var hasAmount: Bool {return self._amount != nil}
  /// Clears the value of `amount`. Subsequent reads from it will return its default value.
  mutating func clearAmount() {self._amount = nil}

  var category: CostSheetEntry.Categoty {
    get {return _category ?? .fuel}
    set {_category = newValue}
  }
  /// Returns true if `category` has been explicitly set.
  var hasCategory: Bool {return self._category != nil}
  /// Clears the value of `category`. Subsequent reads from it will return its default value.
  mutating func clearCategory() {self._category = nil}

  var palce: String {
    get {return _palce ?? String()}
    set {_palce = newValue}
  }
  /// Returns true if `palce` has been explicitly set.
  var hasPalce: Bool {return self._palce != nil}
  /// Clears the value of `palce`. Subsequent reads from it will return its default value.
  mutating func clearPalce() {self._palce = nil}

  /// in dd/mm/yyyy
  var date: String {
    get {return _date ?? String()}
    set {_date = newValue}
  }
  /// Returns true if `date` has been explicitly set.
  var hasDate: Bool {return self._date != nil}
  /// Clears the value of `date`. Subsequent reads from it will return its default value.
  mutating func clearDate() {self._date = nil}

  var id: String {
    get {return _id ?? String()}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  var hasID: Bool {return self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  mutating func clearID() {self._id = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum EntryType: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case income // = 0
    case expense // = 1

    init() {
      self = .income
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .income
      case 1: self = .expense
      default: return nil
      }
    }

    var rawValue: Int {
      switch self {
      case .income: return 0
      case .expense: return 1
      }
    }

  }

  enum Categoty: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case fuel // = 0
    case food // = 2
    case other // = 3

    init() {
      self = .fuel
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .fuel
      case 2: self = .food
      case 3: self = .other
      default: return nil
      }
    }

    var rawValue: Int {
      switch self {
      case .fuel: return 0
      case .food: return 2
      case .other: return 3
      }
    }

  }

  init() {}

  fileprivate var _type: CostSheetEntry.EntryType? = nil
  fileprivate var _amount: Float? = nil
  fileprivate var _category: CostSheetEntry.Categoty? = nil
  fileprivate var _palce: String? = nil
  fileprivate var _date: String? = nil
  fileprivate var _id: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension CostSheetEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "CostSheetEntry"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "type"),
    2: .same(proto: "amount"),
    3: .same(proto: "category"),
    4: .same(proto: "palce"),
    5: .same(proto: "date"),
    6: .same(proto: "id"),
  ]

  public var isInitialized: Bool {
    if self._type == nil {return false}
    if self._amount == nil {return false}
    if self._category == nil {return false}
    if self._date == nil {return false}
    if self._id == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularEnumField(value: &self._type)
      case 2: try decoder.decodeSingularFloatField(value: &self._amount)
      case 3: try decoder.decodeSingularEnumField(value: &self._category)
      case 4: try decoder.decodeSingularStringField(value: &self._palce)
      case 5: try decoder.decodeSingularStringField(value: &self._date)
      case 6: try decoder.decodeSingularStringField(value: &self._id)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._type {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    }
    if let v = self._amount {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 2)
    }
    if let v = self._category {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
    }
    if let v = self._palce {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    }
    if let v = self._date {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    }
    if let v = self._id {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: CostSheetEntry) -> Bool {
    if self._type != other._type {return false}
    if self._amount != other._amount {return false}
    if self._category != other._category {return false}
    if self._palce != other._palce {return false}
    if self._date != other._date {return false}
    if self._id != other._id {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CostSheetEntry.EntryType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "INCOME"),
    1: .same(proto: "EXPENSE"),
  ]
}

extension CostSheetEntry.Categoty: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "FUEL"),
    2: .same(proto: "FOOD"),
    3: .same(proto: "OTHER"),
  ]
}
